apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
  annotations:
    #Нужна для указания дефолтного контейнера
    kubectl.kubernetes.io/default-container: "web-server"
spec:
  #Описание общего каталога
  volumes:
    - name: shared-dir
      emptyDir: {}

  initContainers:
    - name: init-container
      image: alpine
      command: ["bin/sh", "-c"]
      args:
        - echo "<html><body><h1>Homework Pod</h1><p>Создал ручками, аплодируем</p></body></html>" > /init/index.html
      volumeMounts:
        - name: shared-dir
          mountPath: /init

  containers:
    - name: web-server
      image: python:3-alpine
      command: ["/bin/sh", "-c"]
      args:
        - python -m http.server 8000 --directory /homework
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: shared-dir
          mountPath: /homework
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "rm -f /homework/index.html"]
